export const REQUEST_LOCATION  = 'LOCATION_MAP/REQUEST_LOCATION';
export const REQUEST_LOCATION_SUCCESS  = 'LOCATION_MAP/REQUEST_LOCATION_SUCCESS';
export const REQUEST_LOCATION_FAIL  = 'LOCATION_MAP/REQUEST_LOCATION_FAIL';