export const REQUEST_SEARCH_MAP = 'SEARCH_MAP/REQUEST_SEARCH_MAP';
export const REQUEST_SEARCH_MAP_SUCCESS = 'SEARCH_MAP/REQUEST_SEARCH_MAP_SUCCESS';
export const REQUEST_SEARCH_MAP_FAIL = 'SEARCH_MAP/REQUEST_SEARCH_MAP_FAIL';